### ISSUE TITLE
Unable to obtain driver using Selenium Manager

### ISSUE THREAD

**Issue by tiritibambix** [TheLime1/gptCensorFree#13]
Hello,
I've been trying to install gptCensorFree but I got an error while running `python3 token_gen.py`

```
WARNING:selenium.webdriver.common.driver_finder:Unable to obtain driver using Selenium Manager: Selenium Manager failed for: /usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json.
error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE): error trying to connect: tcp connect error: Connection refused (os error 111)
Traceback (most recent call last):
  File "/home/gptCensorFree/token_gen.py", line 20, in <module>
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json.
error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE): error trying to connect: tcp connect error: Connection refused (os error 111)
```

I'm not really educated about this. Does this mean chrome in not installed on my machine ?
What would be the proper way to solve this ?

**Comment by TheLime1** [comment]
try using `python` instead of `python3` , and you need chrome installed in your machine

**Comment by tiritibambix** [comment]
`python` returned an `unknown command` so I used `python3`.

How do I install chrome on my headless debian ?

Shouldn't it be in `requirements.txt` ?

**Comment by TheLime1** [comment]
`requirements.txt`meant for pip packages
you need to installed it by your own
```
# Update the package lists
sudo apt update

# Install dependencies
sudo apt install -y wget curl unzip

# Download Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Install Google Chrome
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Fix missing dependencies
sudo apt --fix-broken install

# Verify installation
google-chrome-stable --version

```

**Comment by tiritibambix** [comment]
Thanks for your help. I got the same error after installing chrome.

Not sure where to look at now :(
